[package]
name = "rust_app"
version = "0.1.0"
authors = ["0xffset"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.7", features = ["mysql"] }
diesel_migrations = "1.4.0"