[package]
name = "rust_app"
version = "0.1.0"
authors = ["0xffset <rene.gottschalk02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.7", features = ["mysql"] }