version: "3.8"

services:
    mysql:
        image: mysql:5.7
        volumes: 
            - mysql_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB}

    program:
        build: 
            context: .
            args:
                RUST_APP: ${RUST_APP}
                DB_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DB}

volumes: 
    mysql_data: