version: "3.8"

services:
    mysql:
        image: mysql:5.7
        volumes: 
            - mysql_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db

    program:
        build: .
        environment: 
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: db

volumes: 
    mysql_data: