version: "3.8"

services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - ${PORT}:3306
        expose:
          - ${PORT}
        volumes:
          - mysql-data:${DATA_DIR}

    program:
        build: 
            context: .
            args:
                RUST_APP: ${RUST_APP}
        environment: 
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DB}

volumes:
    mysql-data:
